variables:
  IMAGE_NAME: junyhehe/ggorangjirang
  IMAGE_TAG: "1.0"

stages:
  - compile
  - test
  - build
  - deploy

compile:
  stage: compile
  before_script: 
    - export PATH="/home/ubuntu/.sdkman/candidates/gradle/current/bin:$PATH"
  script:
    - gradle build --exclude-task test
  tags:
    - compile

test:
  stage: test
  before_script: 
    - echo $PATH
    - export PATH="/home/ubuntu/.sdkman/candidates/gradle/current/bin:$PATH"
  script:
    - gradle build test
  tags:
    - test

build:
  stage: build
  image: docker:26.1.3
  services:
    - docker:26.1.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $DOCKER_REGISTRY_PASS | docker login --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  tags:
    - build

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 34.64.229.17 >> ~/.ssh/known_hosts
  script:
    - ssh elice@34.64.229.17 "cat /etc/os-release"
    - cat /etc/os-release
  tags:
    - deploy
