variables:
  IMAGE_NAME: junyhehe/ggorangjirang
  IMAGE_TAG: "1.0"

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 34.64.229.17 >> ~/.ssh/known_hosts
  script:
    - ssh -i $SSH_KEY elice@34.64.229.17 "echo $DOCKER_REGISTRY_PASS | sudo docker login --username $DOCKER_REGISTRY_USER --password-stdin && docker rm app -f 

  tags:
    - deploy
