spring:
  application:
    name: ggorangjirang

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000 # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Refresh-Token
