spring:
  application:
    name: ggorangjirang

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: 3600000 # 1시간
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Refresh-Token

cloud:
  aws:
    credentials:
      secret-key: ${AWS_S3_SECRET_KEY}
      access-key: ${AWS_S3_ACCESS_KEY}
    s3:
      bucket: ggorangjirang-s3
      upload-temp: images/upload/products/
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'