spring:
  application:
    name: ggorangjirang

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: false

    # 테이블 생성 후 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console.enabled: true

jwt:
  secretKey: mysecrethaha

  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Refresh-Token