name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

env:
  IMAGE_NAME: junyhehe/ggorangjirang
  IMAGE_TAG: 1.0
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
  
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04


    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.SPRING_ENV }}" > ./src/main/resources/env.yml
      - run: echo "${{ secrets.DOCKER_REGISTRY_PASS }}" | docker login --username "${{ secrets.DOCKER_REGISTRY_USER }}" --password-stdin
      - run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - run: docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.64.229.17 >> ~/.ssh/known_hosts
      - run: ssh -i ~/.ssh/id_rsa elice@34.64.229.17 "echo $DOCKER_REGISTRY_PASS | docker login --username $DOCKER_REGISTRY_USER --password-stdin && docker rm app -f || true && docker pull $IMAGE_NAME:$IMAGE_TAG && docker run -d -p 8080:8080 --name app --network elice $IMAGE_NAME:$IMAGE_TAG"

